name: Build

on:
  workflow_dispatch:

jobs:
  BuildAndDockerize:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java-version }}
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          gradle-${{ runner.os }}-
    - name: Gradle Build
      run: ./gradlew build

    - name: Gradle BootJar
      run: ./gradlew bootJar

  DeployStaging:
    runs-on: ubuntu-latest
    needs: BuildAndDockerize
    environment:
      name: staging
    steps:
      - name: Deploy to Staging
        run: |
          echo "This is a mock deployment step to staging."

  TriggerIntegrationTest:
    runs-on: ubuntu-latest
    needs: DeployStaging
    steps:
      - name: Trigger Integration Tests
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.everest-preview+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             https://api.github.com/repos/NeilDuToit92/cicd_test_1/dispatches \
            -d '{"event_type":"run-integration-tests"}'

  PollIntegrationTests:
    runs-on: ubuntu-latest
    needs: TriggerIntegrationTest
    steps:
      - name: Poll Integration Tests Status
        id: poll
        uses: benc-uk/workflow-dispatch@v1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          owner: NeilDuToit92
          repo: https://github.com/NeilDuToit92/cicd_test_1
          workflow_id: integration-tests.yml
          ref: main
          wait_for: true
          wait_interval: 10
          wait_timeout: 600

  DeployProd:
    runs-on: ubuntu-latest
    needs: PollIntegrationTests
    environment:
      name: production
    steps:
      - name: Deploy to Production
        run: |
          echo "This is a mock deployment step to production."