name: Deploy to Prod

on:
  workflow_run:
    workflows: ["Build"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Deploy to Production
        run: |
          ssh -o StrictHostKeyChecking=no user@staging-server "docker service update --image your-docker-repo/your-app:latest your-staging-service"
