name: Build

on:
  workflow_dispatch:

jobs:
  IntegrationTests:
    runs-on: ubuntu-latest
    needs: BuildAndDockerize
    steps:
      - name: Integration tests
        run: |
          echo "This is a mock step for integration tests."