name: IntegrationTests

on:
  repository_dispatch:
    types: [ run-integration-tests ]

jobs:
  IntegrationTests:
    runs-on: ubuntu-latest
    steps:
      - name: Integration tests
        run: |
          echo "This is a mock step for integration tests."